### ISSUE TITLE
Reorganize Plugin, Implement Timeouts

### ISSUE THREAD

**Issue by CodeLenny** [rrdelaney/ava-rethinkdb#11]
`ava-rethinkdb` is currently hanging.  It's consistently hanging on my local machine (Node 8), and is quite flaky in CI (jobs needs to be restarted often).

I'd like to take a slightly drastic approach to fix this.

- [ ] **Move functionality to a separate class (`MockedRethinkDB.js`)**

I'd like to move the actual functionality of the mocking into a separate file.
This will split testing, and let us actually test the functionality of each component, rather than just integration tests which are harder to debug.

- [ ] **Split functionality into separate methods**

The plugin attempts to do many things all in the `init()` stage:

- Select a random port
- Create temporary directory for storage
- Set `DEFAULT_PORT` inside `require("rethinkdb")`
- Spawn RethinkDB, wait for start
- Import data into RethinkDB

As some of these appear to be more stable than others, it would be nice to break each down into a separate method so each stage can be unit-tested separately.  I'd also like to add (configurable) timeouts tweaked for each stage, so CI pipelines won't hang with no additional information.

- [ ] **Add `require("ava-rethinkdb").setup()`**

`init()` is made to be inserted into a single `beforeEach()`.
With the functionality split into separate methods, it could be nice to have a `beforeEach()` statement for each stage to provide more context for debugging (especially if stages timed-out instead of just hanging).  
`setup()` could even contain the `afterEach` for `cleanup()`.

`setup()` would be called in the top-level scope:

```js
const test = require("ava");
const { setup } = require("ava-rethinkdb");

setup();

test(...);
```

Then `setup()` would create each of the `beforeEach()` and `afterEach()` statements needed, and be able to give each a descriptive name to narrow down debugging scope.

I'd retain `init()` for backwards-compatibility, and still have it concatenate each method from `MockedRethinkDB.js` into a single `beforeEach()` stage, but strongly suggest `setup()` in the `README`.

Final thought: it might be better if `setup()` had a name relating to `ava-rethinkdb` so we could use the object unpacking without conflicting with other modules that might want to use `setup()` as a keyword.  
Instead, maybe it should be named `mockRethink()` or something.

## Planned Breaking Changes

I'm currently drafting my work with a few breaking changes for now.  I can tweak the code for many of these if they are troublesome.

- `init()` takes more options than just `initialData`, so `initialData` is a layer deeper in the configuration object.
- `init()` and `cleanup()` need to be used in `beforeEach()` and `afterEach()` instead of `before()` and `after()`.  This allows using `t.context` to store internal information, including the port used, allowing retrying ports.

(@rrdelaney)

**Comment by CodeLenny** [comment]
Hey @rrdelaney I've drafted up what I'm thinking.  Would you mind scanning what I've got to see if it's the right direction or if you've got any suggestions?

https://gist.github.com/CodeLenny/06f07bd7f7216300d95324192d1d2c3f

**Comment by rrdelaney** [comment]
@CodeLenny Can you pull that onto a branch and make a WIP PR so I can add comments inline? Should be easier that way 🙂

**Comment by cavejay** [comment]
Was this PR ready for merge? 
Looking to use something like this in a project and I've noticed the hanging behaviour.

**Comment by rrdelaney** [comment]
@cavejay you probably shouldn't use this library or rethinkdb at this point

**Comment by cavejay** [comment]
ah, disappointing to hear
