### ISSUE TITLE
Error: spawn rethinkdb ENOENT

### ISSUE THREAD

**Issue by jbelmont** [rrdelaney/ava-rethinkdb#3]
When I run the ava-rethinkdb it works but when I ran it through travis CI
I get `Error: spawn rethinkdb ENOENT`

Is there something I am doing wrong or need to add for ci build?

**Comment by rrdelaney** [comment]
Is the rethinkdb executable in the PATH on Travis? This calls the rethinkdb command line tool to spawn new DB's

**Comment by jbelmont** [comment]
@rrdelaney oh wow I never specified rethinkdb in before_install script in travis ci which is why it is blowing up. Sorry for raising an issue not related to your library which works beautifully.

**Comment by rrdelaney** [comment]
Thanks for the kind words!
